### PR TITLE
Initialize coreThread to NULL. Fixes #2

### LINKED ISSUE #2: Segfault when trying to run anything
On the latest CI build - https://github.com/Hydr8gon/NooDS/runs/429011066 - attempting to run anything (firmware or ROMs) causes a segmentation fault. Here's the backtrace:

```
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x7ffff7fafa00 (LWP 9702) "noods" 0x00007ffff68288b4 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
  2    Thread 0x7fffe8c8f700 (LWP 9706) "gmain" 0x00007ffff7af8bf9 in __GI___poll (fds=0x84f590, nfds=2, timeout=4999) at ../sysdeps/unix/sysv/linux/poll.c:29
  3    Thread 0x7fffe3fff700 (LWP 9707) "gdbus" 0x00007ffff7af8bf9 in __GI___poll (fds=0x85adf0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  10   Thread 0x7fffe178d700 (LWP 9714) "threaded-ml" 0x00007ffff7af8bf9 in __GI___poll (fds=0x7fffd0004bc0, nfds=3, timeout=669) at ../sysdeps/unix/sysv/linux/poll.c:29
  11   Thread 0x7fffe0f8c700 (LWP 9715) "noods" 0x00007ffff7af8bf9 in __GI___poll (fds=0x8b8fc0, nfds=1, timeout=22) at ../sysdeps/unix/sysv/linux/poll.c:29
  12   Thread 0x7fffc1aa3700 (LWP 9720) "pool" syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
(gdb) thread apply all bt full

Thread 12 (Thread 0x7fffc1aa3700 (LWP 9720)):
#0  0x00007ffff7aff839 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff4bc989a in g_cond_wait_until () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4b56571 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4babb34 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff4bab195 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff633b6db in start_thread (arg=0x7fffc1aa3700) at pthread_create.c:463
        pd = 0x7fffc1aa3700
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140736442545920, 7777350750093475090, 140736442543360, 0, 10126336, 140737488334432, -7777382196344488686, -7777330445389890286}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007ffff7b0588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 11 (Thread 0x7fffe0f8c700 (LWP 9715)):
#0  0x00007ffff7af8bf9 in __GI___poll (fds=0x8b8fc0, nfds=1, timeout=22) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff6b06835 in  () at /usr/lib/x86_64-linux-gnu/libportaudio.so.2
#2  0x00007ffff6b0760e in  () at /usr/lib/x86_64-linux-gnu/libportaudio.so.2
#3  0x00007ffff633b6db in start_thread (arg=0x7fffe0f8c700) at pthread_create.c:463
        pd = 0x7fffe0f8c700
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140736967788288, 7777350750093475090, 140736967785728, 0, 8733776, 140737488344528, -7777308927960515310, -7777330445389890286}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#4  0x00007ffff7b0588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 10 (Thread 0x7fffe178d700 (LWP 9714)):
#0  0x00007ffff7af8bf9 in __GI___poll (fds=0x7fffd0004bc0, nfds=3, timeout=669) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007fffe806f481 in  () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007fffe8060e40 in pa_mainloop_poll () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#3  0x00007fffe80614d0 in pa_mainloop_iterate () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007fffe8061560 in pa_mainloop_run () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#5  0x00007fffe806f3c9 in  () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007fffe2dd2318 in  () at /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so
#7  0x00007ffff633b6db in start_thread (arg=0x7fffe178d700) at pthread_create.c:463
        pd = 0x7fffe178d700
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140736976180992, 7777350750093475090, 140736976178432, 0, 8994784, 140737488334912, -7777310026935272174, -7777330445389890286}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#8  0x00007ffff7b0588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fffe3fff700 (LWP 9707)):
#0  0x00007ffff7af8bf9 in __GI___poll (fds=0x85adf0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff4b835c9 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4b83962 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff24cb0e6 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff4bab195 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff633b6db in start_thread (arg=0x7fffe3fff700) at pthread_create.c:463
        pd = 0x7fffe3fff700
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140737018590976, 7777350750093475090, 140737018588416, 0, 8210992, 140737488335376, -7777306770276319982, -7777330445389890286}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
---Type <return> to continue, or q <return> to quit---
        not_first_call = <optimized out>
#6  0x00007ffff7b0588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fffe8c8f700 (LWP 9706)):
#0  0x00007ffff7af8bf9 in __GI___poll (fds=0x84f590, nfds=2, timeout=4999) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff4b835c9 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4b836dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4b83721 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff4bab195 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff633b6db in start_thread (arg=0x7fffe8c8f700) at pthread_create.c:463
        pd = 0x7fffe8c8f700
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140737098872576, 7777350750093475090, 140737098870016, 0, 8210832, 140737488334992, -7777326381096993518, -7777330445389890286}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007ffff7b0588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff7fafa00 (LWP 9702)):
#0  0x00007ffff68288b4 in std::thread::join() () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000446e55 in NooFrame::loadRom(wxCommandEvent&) ()
#2  0x00007ffff6f064be in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#3  0x00007ffff6f065c3 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#4  0x00007ffff6f0698b in wxEvtHandler::TryHereOnly(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#5  0x00007ffff6f06a13 in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#6  0x00007ffff6f06a75 in wxEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#7  0x00007ffff75f218b in wxWindowBase::TryAfter(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#8  0x00007ffff6f067d7 in wxEvtHandler::SafelyProcessEvent(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#9  0x00007ffff75a4a8b in wxMenuBase::SendEvent(int, int) () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#10 0x00007ffff74921cb in  () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#11 0x00007ffff4e5e10d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff4e7105e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff4e79715 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff4e7a12f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff5f39006 in gtk_widget_activate () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#16 0x00007ffff5e3607d in gtk_menu_shell_activate_item () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#17 0x00007ffff5e36332 in  () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#18 0x00007ffff5e2438b in  () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#19 0x00007ffff4e5e10d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff4e70de8 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff4e790af in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff4e7a12f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff5f3a2bc in  () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#24 0x00007ffff5e2262c in gtk_propagate_event () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#25 0x00007ffff5e22a2b in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#26 0x00007ffff5a9802c in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#27 0x00007ffff4b83417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff4b83650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff4b83962 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff5e21a37 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#31 0x00007ffff740fb05 in wxGUIEventLoop::DoRun() () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#32 0x00007ffff6dc2a93 in wxEventLoopBase::Run() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#33 0x00007ffff6d8a0a6 in wxAppConsoleBase::MainLoop() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#34 0x00007ffff6e14ae9 in wxEntry(int&, wchar_t**) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#35 0x0000000000413112 in main ()
```

And here's stdout/stderr:

```
granpc@gram:~/Programs$ ./noods 
Gtk-Message: 19:43:28.750: Failed to load module "pantheon-filechooser-module"

(noods:9971): Gtk-WARNING **: 19:43:28.756: Unable to locate theme engine in module_path: "pixmap",

(noods:9971): Gtk-WARNING **: 19:43:28.757: Unable to locate theme engine in module_path: "pixmap",

(noods:9971): Gtk-WARNING **: 19:43:28.757: Unable to locate theme engine in module_path: "pixmap",

(noods:9971): Gtk-WARNING **: 19:43:28.757: Unable to locate theme engine in module_path: "pixmap",
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
Segmentation fault
```

All lines except for "segmentation fault" appear immediately on program startup. The Windows build of the same commit works fine running under wine, with the same firmware and BIOS files.

### PR DESCRIPTION
**Pull request by GranPC**

### CODE REVIEW

File: src/desktop/noo_frame.cpp [hunk 1]
```diff
@@ -34,7 +34,7 @@ EVT_MENU(wxID_EXIT, NooFrame::exit)
 EVT_CLOSE(NooFrame::stop)
 wxEND_EVENT_TABLE()
 
-NooFrame::NooFrame(Emulator *emulator): wxFrame(nullptr, wxID_ANY, "NooDS"), emulator(emulator)
+NooFrame::NooFrame(Emulator *emulator): wxFrame(nullptr, wxID_ANY, "NooDS"), emulator(emulator), coreThread(NULL)
```
Comment (Hydr8gon) [inline src/desktop/noo_frame.cpp]: I'd prefer doing this in the header file instead; there's no reason to use an initializer list to set it to a constant. Also, use nullptr instead of NULL, for consistency with the rest of the code.

File: src/desktop/noo_frame.cpp [hunk 2]
```diff
@@ -82,6 +82,7 @@ void NooFrame::stopCore()
         emulator->running = false;
         coreThread->join();
         delete coreThread;
+        coreThread = NULL;
```
Comment (Hydr8gon) [inline src/desktop/noo_frame.cpp]: Use nullptr instead of NULL here as well.

**Comment by GranPC** [comment]
Done! :)
